// Source des icônes pixel art du site. Chaque dessin est écrit en texte : une ligne = une rangée
// de pixels, une lettre = une couleur de `colors` (palette Endesga 32), "." = transparent.
// Après une modification : `npm run icons` régénère les PNG de public/icons/.

export const colors = {
  k: "#181425", // contour
  d: "#262b44",
  g: "#3a4466",
  G: "#5a6988",
  s: "#8b9bb4",
  S: "#c0cbdc",
  w: "#ffffff",
  p: "#68386c",
  P: "#b55088",
  e: "#3e8948",
  E: "#63c74d",
  b: "#733e39",
  B: "#b86f50",
  K: "#e8b796", // peau
  y: "#feae34",
  Y: "#fee761", // papier du post-it
  r: "#e43b44",
  D: "#a22633",
};

const briefcase = [
  "................",
  "................",
  "................",
  ".....kkkkkk.....",
  ".....kb..bk.....",
  ".....kb..bk.....",
  ".kkkkkkkkkkkkkk.",
  ".kBBBBBBBBBBBBk.",
  ".kBBBBBBBBBBBBk.",
  ".kbbbbbkkbbbbbk.",
  ".kkkkkkyykkkkkk.",
  ".kBBBBBkkBBBBBk.",
  ".kBBBBBBBBBBBBk.",
  ".kbbbbbbbbbbbbk.",
  ".kkkkkkkkkkkkkk.",
  "................",
];

const floppyDisk = [
  "................",
  ".kkkkkkkkkkkkkk.",
  ".kPpkSSSSSSkppk.",
  ".kppkSSSgSSkppk.",
  ".kppkSSSgSSkppk.",
  ".kppkSSSSSSkppk.",
  ".kpppkkkkkkpppk.",
  ".kppppppppppppk.",
  ".kppwwwwwwwwppk.",
  ".kppweeeeeewppk.",
  ".kppwwwwwwwwppk.",
  ".kppwEEEEwwwppk.",
  ".kppwwwwwwwwppk.",
  ".kppwwwwwwwwppk.",
  ".kkkkkkkkkkkkkk.",
  "................",
];

const monitor = [
  "................",
  ".kkkkkkkkkkkkkk.",
  ".kSSSSSSSSSSSSk.",
  ".kSkkkkkkkkkkSk.",
  ".kSkddddddddkSk.",
  ".kSkdddddEddkSk.",
  ".kSkdddddEddkSk.",
  ".kSkdddEdEddkSk.",
  ".kSkdEdEdEddkSk.",
  ".kSkdEdEdEddkSk.",
  ".kSkkkkkkkkkkSk.",
  ".kSSSSSSSSSSESk.",
  ".kkkkkkkkkkkkkk.",
  ".....kssssk.....",
  "...kkkkkkkkkk...",
  "................",
];

const character = [
  "................",
  ".....kkkkkk.....",
  "....kbbbbbbk....",
  "...kbbbbbbbbk...",
  "...kbKKKKKKbk...",
  "...kKKkKKkKKk...",
  "...kKKKKKKKKk...",
  "...kKKKkkKKKk...",
  "....kKKKKKKk....",
  ".....kkKKkk.....",
  "...kkeeKKeekk...",
  "..keeeeeeeeeek..",
  ".keeeeEeeEeeeek.",
  ".keeeeeeeeeeeek.",
  ".kkkkkkkkkkkkkk.",
  "................",
];

const envelope = [
  "................",
  "................",
  "................",
  ".kkkkkkkkkkkkkk.",
  ".kwkwwwwwwwwkwk.",
  ".kwwkwwwwwwkwwk.",
  ".kwwwkwwwwkwwwk.",
  ".kwwwwkPPkwwwwk.",
  ".kwwwwwkkwwwwwk.",
  ".kwwwwwwwwwwwwk.",
  ".kSSSSSSSSSSSSk.",
  ".kkkkkkkkkkkkkk.",
  "................",
  "................",
  "................",
  "................",
];

const medal = [
  "................",
  "..kkkk....kkkk..",
  "..kPPPk..kPPPk..",
  "...kPPPkkPPPk...",
  "....kPPPPPPk....",
  ".....kkkkkk.....",
  "....kyyyyyyk....",
  "...kywyyyyyyk...",
  "..kywyyyyyyyyk..",
  "..kyyyyyyyyyBk..",
  "..kyyyyyyyyyBk..",
  "...kyyyyyyyBk...",
  "....kBBBBBBk....",
  ".....kkkkkk.....",
  "................",
  "................",
];

const spreadsheet = [
  "................",
  ".kkkkkkkkkkkkkk.",
  ".kPPPkPPPkPPPPk.",
  ".kkkkkkkkkkkkkk.",
  ".kSSSkwwwkwwwwk.",
  ".kSSSkwEwkwwwwk.",
  ".kSSSkwwwkwwwwk.",
  ".kkkkkkkkkkkkkk.",
  ".kSSSkwwwkwwwwk.",
  ".kSSSkwwwkwwEwk.",
  ".kSSSkwwwkwwwwk.",
  ".kkkkkkkkkkkkkk.",
  ".kSSSkwwwkwwwwk.",
  ".kSSSkwEwkwEwwk.",
  ".kkkkkkkkkkkkkk.",
  "................",
];

const textFile = [
  "................",
  "..kkkkkkkkk.....",
  "..kwwwwwwwkk....",
  "..kwwwwwwwkSk...",
  "..kwwwwwwwkkkk..",
  "..kwgggggwwwwk..",
  "..kwwwwwwwwwwk..",
  "..kwggggggggwk..",
  "..kwwwwwwwwwwk..",
  "..kwgggggggwwk..",
  "..kwwwwwwwwwwk..",
  "..kwggggggggwk..",
  "..kwwwwwwwwwwk..",
  "..kwwwwwwwwwwk..",
  "..kkkkkkkkkkkk..",
  "................",
];

const trash = [
  "................",
  "......kkkk......",
  "..kkkkkSSkkkkk..",
  "..kSSSSSSSSSSk..",
  "..kkkkkkkkkkkk..",
  "...kSsSsSsSsk...",
  "...kSsSsSsSsk...",
  "...kSsSsSsSsk...",
  "...kSsSsSsSsk...",
  "...kSsSsSsSsk...",
  "...kSsSsSsSsk...",
  "...kSsSsSsSsk...",
  "....kSsSsSsk....",
  "....kkkkkkkk....",
  "................",
  "................",
];

const pushpin = [
  "...kkkk...",
  "..krrwrk..",
  ".krrrrrrk.",
  ".krrrrrrk.",
  "..kDDDDk..",
  "...kDDk...",
  "....ks....",
  "....ks....",
  "....k.....",
];

const stickyNote = [
  "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
  "kyyyyyyyyyyyyyyyyyyyyyyyyyyyyk",
  "kyyyyyyyyyyyyyyyyyyyyyyyyyyyyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYYYYYYYYyk",
  "kYYYYYYYYYYYYYYYYYYYYkkkkkkkkk",
  "kYYYYYYYYYYYYYYYYYYYYkyyyyyyk.",
  "kYYYYYYYYYYYYYYYYYYYYkyyyyyk..",
  "kYYYYYYYYYYYYYYYYYYYYkyyyyk...",
  "kYYYYYYYYYYYYYYYYYYYYkyyyk....",
  "kYYYYYYYYYYYYYYYYYYYYkyyk.....",
  "kYYYYYYYYYYYYYYYYYYYYkyk......",
  "kyyyyyyyyyyyyyyyyyyyykk.......",
  "kkkkkkkkkkkkkkkkkkkkkk........",
];

const padlock = [
  "................",
  ".....kkkkkk.....",
  "....kSSSSSSk....",
  "....kSkkkkSk....",
  "....kSk..kSk....",
  "....kSk..kSk....",
  "...kkkkkkkkkk...",
  "...kyyyyyyyyk...",
  "...kyyykkyyyk...",
  "...kyyykkyyyk...",
  "...kyyyykyyyk...",
  "...kBBBBBBBBk...",
  "...kkkkkkkkkk...",
  "................",
  "................",
  "................",
];

const arrowLeft = [
  "........",
  "....S...",
  "...SS...",
  "..SSS...",
  ".SSSS...",
  "..SSS...",
  "...SS...",
  "....S...",
];

const arrowRight = [
  "........",
  "...S....",
  "...SS...",
  "...SSS..",
  "...SSSS.",
  "...SSS..",
  "...SS...",
  "...S....",
];

/** Nom du fichier PNG (public/icons/<nom>.png) → dessin. */
export const icons = {
  "briefcase": briefcase,
  "floppy-disk": floppyDisk,
  "monitor": monitor,
  "character": character,
  "envelope": envelope,
  "medal": medal,
  "spreadsheet": spreadsheet,
  "text-file": textFile,
  "trash": trash,
  "pushpin": pushpin,
  "sticky-note": stickyNote,
  "padlock": padlock,
  "arrow-left": arrowLeft,
  "arrow-right": arrowRight,
};
